import React from "react";
import { HTMLContent } from "../components/Content";

const ContestPage = ({ data }) => {
  return (
    <div
      style={{
        paddingLeft: 100,
        paddingRight: 100,
        minHeight: 200,
        paddingTop: 150
      }}
    >
      <HTMLContent
        content={`
        <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size: 20pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">OFFICIAL RULES</span></p>
        <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Important: Please read these Official Rules before entering this online promotion (the “Promotion”). By participating in the Promotion, you agree to be bound by these Official Rules and represent that you satisfy all of the eligibility requirements below.</span></p>
        <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:12pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">NO PURCHASE, PAYMENT, OR FINANCIAL CONTRIBUTION OF ANY KIND IS NECESSARY TO ENTER OR WIN THIS PROMOTION.</span></p>
        <ul style="margin-top:0;margin-bottom:0;">
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Eligibility.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;PURCHASE, PAYMENT OR FINANCIAL CONTRIBUTION WILL NOT INCREASE ODDS OF WINNING. PROMOTION VOID WHERE PROHIBITED. PROMOTION OPEN ONLY TO INDIVIDUAL UNITED STATES CITIZENS AND LAWFUL PERMANENT U.S. RESIDENTS WHO ARE LEGAL RESIDENTS OF THE FIFTY (50) UNITED STATES, THE DISTRICT OF COLUMBIA AND PUERTO RICO, AND OVER THE AGE OF 18 (OR THE AGE OF MAJORITY UNDER APPLICABLE LAW). BUSINESSES, CORPORATIONS, OR OTHER ENTITIES ARE NOT ELIGIBLE TO ENTER OR WIN A PRIZE, NOR MAY ANY INDIVIDUAL ENTER ON BEHALF OF ANY SUCH INDIVIDUALS OR ENTITIES. IF YOU DO NOT MEET ANY OF THESE REQUIREMENTS, OR ANY OTHER ELIGIBILITY REQUIREMENTS IN THESE OFFICIAL RULES, YOU ARE NOT ELIGIBLE TO WIN A PRIZE, AND JUSTICE DEMOCRATS (“SPONSOR”) RESERVES THE RIGHT NOT TO AWARD PRIZES TO YOU. To be eligible to win the prize, entries must be completed and received by Sponsor in the format designated below. Directors, officers and employees of Sponsor and any of their respective affiliated committees, subsidiaries, agents, professional advisors, consultants, advertising and promotional agencies, and immediate families of each are not eligible to win any prizes. All applicable federal, state and local laws and regulations apply.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Disclaimer.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Sponsor, and its related committees, candidate(s), affiliates, directors, officers, consultants, professional advisors, employees and agents (collectively, the “Released Parties”) will not be responsible for: (a) any late, lost, misrouted, garbled or distorted or damaged transmissions or entries; (b) telephone, electronic, hardware, software, network, Internet, or other computer- or communications-related malfunctions or failures; (c) any Promotion disruptions, injuries, losses or damages caused by events beyond the control of Sponsor or by non-authorized human intervention; or (d) any printing or typographical errors in any materials associated with the Promotion.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Promotion Period.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;The Promotion starts at 12:00 a.m. Eastern Time on December 27, 2019 and ends at 11:59 p.m. Eastern Time on December 31, 2019 (the “Promotion Period”). All entries must be received during the Promotion Period to be eligible to win a prize.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>Prizes.
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;One (1) winner will receive the following prize: one signed Justice Democrats branded t-shirt. Approximate retail value:&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">$35.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Sponsor will choose, in its sole discretion, prize logistics and details.&nbsp;</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>Odds; Taxes; Etc.
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Odds of winning a prize depend on the number and quality of eligible entries received.&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">ALL FEDERAL, STATE AND LOCAL TAXES ASSOCIATED WITH THE RECEIPT OR USE OF ANY PRIZE ARE THE SOLE RESPONSIBILITY OF WINNERS. All prizes will be awarded.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;A prize may be forfeited and awarded to an alternative winner if (a) the winner affidavit and release materials (see Sections 10 and 11 below) are not returned as required from the potential winner, (b) if two (2) attempts to contact the potential winner by phone and/or e-mail are not successful, or if (c) any prize is otherwise not claimed. Prizes are not transferable. No substitutions or exchanges (including for cash) of any prizes will be permitted, except that Sponsor reserves the right to substitute a prize of equal or greater value for any prize. Limit one prize per household or address. All prizes are awarded “AS IS” and WITHOUT WARRANTY OF ANY KIND, express or implied (including, without limitation, any implied warranty of merchantability or fitness for a particular purpose).</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Identity of Entrant.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;In the event of a dispute about the identity of the entrant, entries made online will be declared made by the authorized account holder of the e-mail address submitted at time of entry. An authorized account holder is defined as the natural person who is assigned to an e-mail address by an Internet access provider, online service provider or other organization (e.g., business, educational institution, etc.) that is responsible for assigning e-mail addresses for the domain associated with the submitted e-mail address. The potential winner may be required to provide Sponsor with proof that the potential winner is the authorized account holder of the e-mail address associated with the winning entry.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>How to Enter.
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Participants may enter as follows: (a) Free Online Entry Method: To enter via the free online entry method, visit</span>
              <a href="https://go.justicedemocrats.com/signup/jdem-20191227-tshirt-ro/" style="text-decoration:none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;here</span></a><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;or other web page specifically identified by Sponsor and complete and submit the online entry form during the Promotion Period. (b) Contribution Method: To enter by contributing money to Justice Democrats, complete and submit the contribution form</span>
              <a href="https://secure.actblue.com/donate/jdem-ro-khanna-entry" style="text-decoration:none;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;here</span></a><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;or other web page specifically identified by Sponsor during the Promotion Period. No minimum contribution is necessary to enter. Entering via the contribution method described in this paragraph (b) will not increase your chances of winning the prize. Contributions may be spent on any activities of Sponsor as it determines in its sole discretion.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>For All Entry Methods:
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Failure to submit all required information in the manner required in these Official Rules and/or any entry or contribution form may result in disqualification. Proof of contribution or online entry will not be deemed to be proof of receipt of entry by Sponsor. All entrants and entries are subject to verification by Sponsor. Entries will not be acknowledged or returned. By entering the Promotion, you consent to being placed on an e-mail mailing list to receive information from Sponsor and for other purposes in accordance with Sponsor's Privacy Policy. Individuals may not enter the Promotion by any and all methods combined more than ten (10) times in any calendar day.&nbsp;</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Promotion Rules.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Twenty (20) potential winners will be selected by a random drawing from all eligible entries to be held by January 15, 2020. Sponsor may, at its option, conduct a background check on each potential winner. Sponsor reserves the right to disqualify any potential winner from receiving any prize based on such background check if Sponsor determines, in its sole discretion, that awarding any prize to such potential winner could result in a safety or security risk to any person or persons. Sponsor will, in its sole discretion, then select four (4) winners from the list of eligible potential winners on the basis of criteria determined and applied by Sponsor to provide for an appropriate range of views, backgrounds, and interests. Winners will be notified by phone or e-mail by January 20, 2020. To claim the prize, winners should follow the instructions and comply with the conditions contained in their notification. In the event that not enough potential winners respond to Sponsor's attempts to contact them or are otherwise disqualified such that Sponsor is unable to award all prizes, Sponsor may select additional potential winners by random drawing from remaining eligible entries.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">General Release. By entering the Promotion, you release Sponsor and all Released Parties from any liability whatsoever, and waive any and all causes of action, related to any claims, costs, injuries, losses, or damages of any kind arising out of or in connection with the Promotion or delivery, misdelivery, acceptance, possession, use of or inability to use any prize (including, without limitation, claims, costs, injuries, losses and damages related to personal injuries, death, damage to or destruction of property, rights of publicity or privacy, defamation or portrayal in a false light, whether intentional or unintentional), whether under a theory of contract, tort (including negligence), warranty or other theory.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Use of Winner Name, Likeness, etc.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Except where prohibited by law, entry into the Promotion constitutes permission to use winner's name, hometown, likeness and/or prize information, without limitation, for promotional purposes without further permission or compensation. As a condition of being awarded any prize, except where prohibited by law, winner may be required to execute a consent to the use of his or her name, hometown, likeness and/or prize information, without limitation, for promotional purposes without further permission or compensation.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Affidavit &amp; Release.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;As a condition of being awarded any prize, winners may be required to execute and deliver to Sponsor a signed affidavit of eligibility and acceptance of these Official Rules and release of liability, and any other legal, regulatory, or tax-related documents required by Sponsor in its sole discretion.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>Winner List; Rules Request.
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;For a copy of the winner list, send a stamped, self-addressed, business-size envelope after January 1, 2020 and before January 1, 2021 to Sponsor at the address listed below, Attn:&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">“Justice Democrats T-Shirt Contest”</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Winner List. To obtain a copy of these Official Rules, &nbsp;send a stamped, self-addressed business-size envelope to Sponsor at the address listed below, Attn:&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">“Justice Democrats T-Shirt Contest”</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Rules Request. Residents of VT may omit return postage.</span></p>
          </li>
          <li dir="ltr" style="list-style-type:none;font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;">
            <p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 12pt 0pt;"><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
                <br>
              </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Intellectual Property Notice.</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;The Promotion and all accompanying materials are copyright © 2019 by Justice Democrats. All rights reserved.</span></p>
          </li>
        </ul>
        <p><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
            <br>Miscellaneous.
          </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;The Promotion and these Official Rules will be governed, construed and interpreted under the laws of the District of Columbia without regard to its or any other jurisdiction's choice of law provisions. Entrants agree to be bound by these Official Rules and by the decisions of Sponsor, which are final and binding in all respects. Any provision of these Official Rules deemed unenforceable will be enforced to the extent permissible, and the remainder of these Official Rules will remain in effect. Sponsor reserves the right to change these Official Rules at any time, in its sole discretion, and to suspend or cancel the Promotion or any entrant's participation in the Promotion should viruses, bugs, unauthorized human intervention or other causes beyond Sponsor's control affect the administration, security or proper play of the Promotion, or Sponsor otherwise becomes (as determined in its sole discretion) incapable of running the Promotion as planned. Entrants who violate these Official Rules, violate any law, rule or regulation in connection with participation in the Promotion, tamper with the operation of the Promotion or engage in any conduct that is detrimental or unfair to Sponsor, the Promotion or any other entrant (in each case as determined in Sponsor's sole discretion) are subject to disqualification from entry into the Promotion. Sponsor reserves the right to lock out persons whose eligibility is in question or who have been disqualified or are otherwise ineligible to enter the Promotion. If you have any questions about these Official Rules or the Promotion, please e-mail them to us@justicedemocrats.com or send written questions to the address listed below, Attn:&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">“Justice Democrats T-Shirt Contest”</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;Questions.
            <br>
          </span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Sponsor</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">:&nbsp;</span><span style="font-size: 12pt; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Justice Democrats, P.O Box 910, Knoxville, TN 37901</span></p>
      `}
        className="medium-m standard-text"
      />
    </div>
  );
};

export default ContestPage;
